### ISSUE TITLE
Site is not autodeployed to gh-pages

### ISSUE THREAD

**Issue by krzysztofzuraw** [WrocTypeScript/website#11]

**Comment by hasparus** [comment]
Okay, it's deployed to Netlify now (kinda easier to configure) and it has deploy previews.
We can move forward in three directions:
- Still deploy to ghpages manually. (Leave it as it is)
- Copy CNAME do Netlify production build.
- Configure automatic deploy to gh-pages.

**Comment by karol-majewski** [comment]
I still hope they will make GitHub Actions public soon and all it will take is enabling the Netlify/GitHub Pages one.

https://github.com/netlify/actions/tree/master/build
