### ISSUE TITLE
Add All contributors and README

### ISSUE THREAD

**Issue by karol-majewski** [WrocTypeScript/website#17]

**Comment by hasparus** [comment]
@all-contributors please add @karol-majewski, @blackdahila and @hasparus for code

**Comment by hasparus** [comment]
@all-contributors please add @karol-majewski for code

**Comment by hasparus** [comment]
@all-contributors please add @blackdahila for code
 @all-contributors please add @hasparus for code

**Comment by hasparus** [comment]
@all-contributors please add @blackdahila for code

**Comment by hasparus** [comment]
@all-contributors please add @hasparus for code

**Comment by hasparus** [comment]
@all-contributors please add @hasparus for code
